 See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
      args: ["--maxkb=2000"]
    - id: detect-private-key
    - id: trailing-whitespace
    - id: end-of-file-fixer
